services:
  sender-cheaas:
    build: .
    stdin_open: true
    command: ["--input", "/opt/data/payload.json"]
    tty: true
    volumes:
      - ./data:/opt/data/:ro
    container_name: sender-cheaas
