apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensinact.fullname" . }}
  labels:
    {{- include "sensinact.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.targetPort .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "sensinact.selectorLabels" . | nindent 4 }}
